apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-98815185-c02-03
  namespace: oci-98815185-c02-03                      
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: mystifying_banach
          image: iad.ocir.io/ocuocictrng19/my_web_app:latest 
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ocir-secret-98815185    
---
apiVersion: v1
kind: Service
metadata:
  name: svc-98815185-c02-03           
  namespace: oci-98815185-c02-03                
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
